[package]
name = "oxide"
version = "0.1.0"
authors = ["jonnu <jontce@gmail.com>"]
edition = "2018"
homepage = "https://github.com/jonnu/oxide"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
